src/GUI/User_GUI.java

test commit / gui mod

---

src/DAO/User_DAO.java
src/DTO/Admin_DTO.java
src/DTO/Info_DTO.java
src/DTO/Training_DTO.java
src/DTO/User_DTO.java

DAO
traning, user 전체보기, 검색, 등록
DTO
객체 선언 - admin 등

baek's DAO&DTO init

---

src/GUI/Admin_GUI.java
src/GUI/User_GUI.java

User_GUI 관리자 메뉴 추가 : Admin_GUI로 넘어가게 함
Admin_GUI 각 메뉴 디자인 구현 완료(* 폰트 추가해야함)

User_GUI 수정 및 Admin_GUI 생성

---

src/DAO/User_DAO.java
src/GUI/Admin_GUI.java
src/GUI/Manager_GUI.java
src/GUI/Users_GUI.java
src/Rank/Main.java

USER_GUI  -> Manager_GUI 이름 변경
Users_GUI 추가
User_DAO 수정

GUI & DAO 수정

---

src/DAO/Admin_DAO.java
src/DAO/Manger_DAO.java
src/DAO/User_DAO.java

분할된 각 DAO 기능추가

---

.classpath
src/DAO/Manger_DAO.java
src/DTO/User_DTO.java
src/GUI/Admin_GUI.java
src/GUI/Manager_GUI.java
src/GUI/Users_GUI.java

Author : seung
Manager_DAO 에러 Catch!
그 외 나머지 기능 정상 작동 확인

GUI <-> DAO 연결 테스트

---

src/DAO/Admin_DAO.java
src/DAO/Manger_DAO.java
src/DAO/User_DAO.java

User_DAO의 rank메서드 sql문 최종 수정완료.
각 DAO의 getInstance메서드 수정완료.

랭킹 쿼리문 최신화 및 DAO 코드수정

---

.classpath
src/DAO/Admin_DAO.java
src/GUI/Admin_GUI.java

 Admin_DAO <-> Admin_GUI 기능 추가

---

src/DAO/Manger_DAO.java

Manager_DAO 수정
→ login 메서드 코드 수정(리턴값 변경)

로그인 메서드 수정

---

src/GUI/Manager_GUI.java
src/GUI/Users_GUI.java

Manager_DAO
→ login 메서드 NullPoint 오류 해결

로그인 메서드 문제 해결

---

.classpath
src/GUI/Admin_GUI.java
src/GUI/Manager_GUI.java

JFrame close 방식 변환
각 Panel 간 전환 방식 변환

Admin, Manager GUI 수정

---

.classpath
src/DAO/User_DAO.java
src/DTO/Info_DTO.java
src/GUI/Users_GUI.java

Users_GUI - 로그아웃 기능 추가, 누적기록, 기록 등록, 랭킹 기현 구현
User_DAO - getInstance 메서드 추가, infoOne  메서드 수정

Users_GUI 연동

---

.classpath
src/DAO/User_DAO.java
src/GUI/Admin_GUI.java
src/GUI/Manager_GUI.java
src/GUI/Users_GUI.java

DAO & GUI 각자 작업 merge

---

src/DAO/Manager_DAO.java
src/DAO/User_DAO.java
src/GUI/Manager_GUI.java

User_DAO 최종수정

---

src/DTO/Admin_DTO.java
src/DTO/Info_DTO.java
src/GUI/Admin_GUI.java
src/GUI/Manager_GUI.java
src/GUI/Users_GUI.java

각 메서드 및 변수 주석 설명 추가

---

README.md
src/GUI/Manager_GUI.java

README 중간 저장

---

.classpath
src/DAO/Admin_DAO.java
src/DAO/Manager_DAO.java
src/DAO/User_DAO.java
src/GUI/Admin_GUI.java
src/GUI/Manager_GUI.java
src/GUI/Users_GUI.java

모든 GUI 오류 메세지 코드 작성 완료
모든 DAO 싱글턴 작업 완료.

GUI 오류 최소화 작업

---

.classpath
README.md
src/GUI/Admin_GUI.java
src/GUI/Manager_GUI.java
src/GUI/Users_GUI.java

README 최종 수정

---

src/DAO/Admin_DAO.java
src/DAO/Manager_DAO.java
src/DAO/User_DAO.java
src/DTO/User_DTO.java
src/GUI/Admin_GUI.java
src/GUI/Manager_GUI.java
src/GUI/Users_GUI.java

User_DTO → 체급(몸무게) 속성 변경(integer > String)
User_DAO → 체급별 랭킹 메서드 추가
User_GUI → 체급별 랭킹 시스템 구현

체급 속성 추가 및 랭킹시스템 수정

---

src/GUI/Users_GUI.java
src/Rank/Main.java

GUI 출력 중 South 패널에 "null 님 안녕하세요"이라고 뜨는 문제를 해결

South Panel null 출력 오류 해결

---

README.md

README 진짜 최종
